### ISSUE TITLE
The browser was not opened when start the service

### ISSUE THREAD

**Issue by halisihan** [trietphm/chatgpt-slackbot#1]
after did 'yarn start', the browser was not opened when start the service and it seems that doesn't work, what can be done to check.

**Comment by trietphm** [comment]
Hi @halisihan, are you using branch `master`? That branch is using the OpenAI API (not the ChatGPT web scraper), so there will be no browser any more, but you can still use the app. Please check the note at https://github.com/trietphm/chatgpt-slackbot/blob/master/README.md#chatgpt-for-slack for the reasons.

And yes, I forgot to update the part on README that saying the browser will open. I will update it soon.
